services:

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  nodejs:
    build: 
      context: .
      dockerfile: nodejs.Dockerfile
    volumes:
      - .:/app