services:

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
    ports:
      - "80:80"

  nodejs:
    build: 
      context: .
      dockerfile: nodejs.Dockerfile
    volumes:
      - .:/app