# name: cicd

# on:
#   push:
#       branches: [main]

# jobs:

#   gcp-vm-sysadmin:
#     name: gcp-vm-sysadmin
#     runs-on: ubuntu-latest
#     steps:
#     - name: sysadmin ops on GCP VM
#       uses: appleboy/ssh-action@v1.0.1
#       env:
#         DEBIAN_FRONTEND: "noninteractive"
#       with:
#         # should be the IP address of your VM
#         host: ${{ secrets.SSH_HOST }}
#         key: ${{ secrets.SSH_PRIV_KEY }}
#         port: 22
#         username: root
#         script_stop: true
#         # all the commands you see after the `|` will be executed in the remote machine
#         script: |
#             cd /var/www/html
#             touch test.txt
#             echo "I WAS UPDATED" > test.txt
